[package]
name = "faucet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
bytes = "1.4.0"
clap = { version = "4.3.22", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.28"
hyper = { version = "0.14.27", features = ["full"] }
log = "0.4.20"
num_cpus = "1.16.0"
tokio = { version = "1.32.0", features = ["full"] }
