[package]
name = "faucet"
version = "0.2.1"
edition = "2021"
authors = ["Andrés F. Quintero <afquinteromoreano@gmail.com>"]
description = "Welcome to Faucet, your go-to solution for deploying Plumber APIs and Shiny Applications with blazing speed and efficiency. Faucet is a high-performance server built with Rust, offering Round Robin and Round Robin + IP Hash load balancing for seamless scaling and distribution of your R applications. Whether you're a data scientist, developer, or DevOps enthusiast, Faucet streamlines the deployment process, making it easier than ever to manage replicas and balance loads effectively."
license = "MIT"
homepage = "https://github.com/andyquinterom/Faucet"

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.4.10", features = ["derive", "env"] }
env_logger = "0.10.1"
log = "0.4.20"
num_cpus = "1.16.0"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = { version = "^0.7", features = ["codec"] }
