[package]
name = "faucet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.4.10", features = ["derive", "env"] }
env_logger = "0.10.1"
log = "0.4.20"
num_cpus = "1.16.0"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = { version = "^0.7", features = ["codec"] }
